// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using Furnace.Forge.Data.ForgeManifest;
//
//    var forgeManifest = ForgeManifest.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace Furnace.Forge.Data.ForgeManifest
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class ForgeManifest
    {
        [JsonPropertyName("_comment_")]
        public string[] Comment { get; set; }

        [JsonPropertyName("spec")]
        public long Spec { get; set; }

        [JsonPropertyName("profile")]
        public string Profile { get; set; }

        [JsonPropertyName("version")]
        public string Version { get; set; }

        [JsonPropertyName("path")]
        public object Path { get; set; }

        [JsonPropertyName("minecraft")]
        public string Minecraft { get; set; }

        [JsonPropertyName("serverJarPath")]
        public string ServerJarPath { get; set; }

        [JsonPropertyName("data")]
        public Dictionary<string, Datum> Data { get; set; }

        [JsonPropertyName("processors")]
        public Processor[] Processors { get; set; }

        [JsonPropertyName("libraries")]
        public Library[] Libraries { get; set; }

        [JsonPropertyName("icon")]
        public string Icon { get; set; }

        [JsonPropertyName("json")]
        public string Json { get; set; }

        [JsonPropertyName("logo")]
        public string Logo { get; set; }

        [JsonPropertyName("mirrorList")]
        public Uri MirrorList { get; set; }

        [JsonPropertyName("welcome")]
        public string Welcome { get; set; }
    }

    public partial class Datum
    {
        [JsonPropertyName("client")]
        public string Client { get; set; }

        [JsonPropertyName("server")]
        public string Server { get; set; }
    }

    public partial class Library
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("downloads")]
        public Downloads Downloads { get; set; }
    }

    public partial class Downloads
    {
        [JsonPropertyName("artifact")]
        public Artifact Artifact { get; set; }
    }

    public partial class Artifact
    {
        [JsonPropertyName("path")]
        public string Path { get; set; }

        [JsonPropertyName("url")]
        public Uri Url { get; set; }

        [JsonPropertyName("sha1")]
        public string Sha1 { get; set; }

        [JsonPropertyName("size")]
        public long Size { get; set; }
    }

    public partial class Processor
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("sides")]
        public string[] Sides { get; set; }

        [JsonPropertyName("jar")]
        public string Jar { get; set; }

        [JsonPropertyName("classpath")]
        public string[] Classpath { get; set; }

        [JsonPropertyName("args")]
        public string[] Args { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("outputs")]
        public Outputs Outputs { get; set; }
    }

    public partial class Outputs
    {
        [JsonPropertyName("{MC_SLIM}")]
        public string McSlim { get; set; }

        [JsonPropertyName("{MC_EXTRA}")]
        public string McExtra { get; set; }
    }

    public partial class ForgeManifest
    {
        public static ForgeManifest FromJson(string json) => JsonSerializer.Deserialize<ForgeManifest>(json, Furnace.Forge.Data.ForgeManifest.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ForgeManifest self) => JsonSerializer.Serialize(self, Furnace.Forge.Data.ForgeManifest.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
            get => _dateTimeStyles;
            set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
            get => _dateTimeFormat ?? string.Empty;
            set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
            get => _culture ?? CultureInfo.CurrentCulture;
            set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
            string text;


            if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
            {
                value = value.ToUniversalTime();
            }

            text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

            writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? dateText = reader.GetString();

            if (string.IsNullOrEmpty(dateText) == false)
            {
                if (!string.IsNullOrEmpty(_dateTimeFormat))
                {
                    return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                }
                else
                {
                    return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                }
            }
            else
            {
                return default(DateTimeOffset);
            }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
