// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using Furnace.Fabric.Data.FabricLoaderMeta;
//
//    var fabricLoaderMeta = FabricLoaderMeta.FromJson(jsonString);
#nullable enable
using Furnace.Utility;

#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace Furnace.Fabric.Data.FabricLoaderMeta
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class FabricLoaderMeta
    {
        [JsonPropertyName("loader")]
        public Loader Loader { get; set; }

        [JsonPropertyName("intermediary")]
        public Intermediary Intermediary { get; set; }

        [JsonPropertyName("launcherMeta")]
        public LauncherMeta LauncherMeta { get; set; }
    }

    public partial class Intermediary
    {
        [JsonPropertyName("maven")]
        public string Maven { get; set; }

        [JsonPropertyName("version")]
        public string Version { get; set; }

        [JsonPropertyName("stable")]
        public bool Stable { get; set; }
    }

    public partial class LauncherMeta
    {
        [JsonPropertyName("version")]
        public long Version { get; set; }

        [JsonPropertyName("libraries")]
        public Libraries Libraries { get; set; }

        [JsonPropertyName("mainClass")]
        public MainClass MainClass { get; set; }
    }

    public partial class Libraries
    {
        [JsonPropertyName("client")]
        public Library[] Client { get; set; }

        [JsonPropertyName("common")]
        public Library[] Common { get; set; }

        [JsonPropertyName("server")]
        public Library[] Server { get; set; }
    }

    public partial class Library
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("url")]
        public Uri Url { get; set; }
    }

    public partial class MainClass
    {
        [JsonPropertyName("client")]
        public string Client { get; set; }

        [JsonPropertyName("server")]
        public string Server { get; set; }
    }

    public partial class Loader
    {
        [JsonPropertyName("separator")]
        public string Separator { get; set; }

        [JsonPropertyName("build")]
        public long Build { get; set; }

        [JsonPropertyName("maven")]
        public string Maven { get; set; }

        [JsonPropertyName("version")]
        public string Version { get; set; }

        [JsonPropertyName("stable")]
        public bool Stable { get; set; }
    }

    public partial class FabricLoaderMeta : IJsonConvertable<FabricLoaderMeta>
    {
        public static FabricLoaderMeta FromJson(string json) => JsonSerializer.Deserialize<FabricLoaderMeta>(json, Furnace.Fabric.Data.FabricLoaderMeta.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this FabricLoaderMeta self) => JsonSerializer.Serialize(self, Furnace.Fabric.Data.FabricLoaderMeta.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
            get => _dateTimeStyles;
            set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
            get => _dateTimeFormat ?? string.Empty;
            set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
            get => _culture ?? CultureInfo.CurrentCulture;
            set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
            string text;


            if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
            {
                value = value.ToUniversalTime();
            }

            text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

            writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? dateText = reader.GetString();

            if (string.IsNullOrEmpty(dateText) == false)
            {
                if (!string.IsNullOrEmpty(_dateTimeFormat))
                {
                    return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                }
                else
                {
                    return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                }
            }
            else
            {
                return default(DateTimeOffset);
            }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
