// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Yggdrasil.Json;
//
//    var authenticateRequest = AuthenticateRequest.FromJson(jsonString);

namespace Furnace.Yggdrasil.Json.Authenticate
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class AuthenticateRequest
    {
        [JsonProperty("agent")]
        public Agent Agent { get; set; }

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("password")]
        public string Password { get; set; }

        [JsonProperty("clientToken")]
        public string ClientToken { get; set; } // Optional

        [JsonProperty("requestUser")]
        public bool RequestUser { get; set; }
    }

    public partial class Agent
    {
        [JsonProperty("name")]
        public string Name { get; set; } = "Minecraft";

        [JsonProperty("version")]
        public long Version { get; set; } = 1;
    }

    public partial class AuthenticateRequest
    {
        public static AuthenticateRequest FromJson(string json) => JsonConvert.DeserializeObject<AuthenticateRequest>(json, Yggdrasil.Json.Authenticate.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this AuthenticateRequest self) => JsonConvert.SerializeObject(self, Yggdrasil.Json.Authenticate.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}

