// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Furnace.Yggdrasil.Json.Error;
//
//    var yggdrasilError = YggdrasilError.FromJson(jsonString);

namespace Furnace.Yggdrasil.Json.Error
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class YggdrasilError
    {
        [JsonProperty("error")]
        public string Error { get; set; }

        [JsonProperty("errorMessage")]
        public string ErrorMessage { get; set; }

        [JsonProperty("cause")]
        public string Cause { get; set; }
    }

    public partial class YggdrasilError
    {
        public static YggdrasilError FromJson(string json) => JsonConvert.DeserializeObject<YggdrasilError>(json, Furnace.Yggdrasil.Json.Error.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this YggdrasilError self) => JsonConvert.SerializeObject(self, Furnace.Yggdrasil.Json.Error.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
