// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Yggdrasil.Json;
//
//    var validateRequest = ValidateRequest.FromJson(jsonString);

namespace Furnace.Yggdrasil.Json.Validate
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ValidateRequest
    {
        [JsonProperty("accessToken")]
        public string AccessToken { get; set; }

        [JsonProperty("clientToken")]
        public string ClientToken { get; set; }
    }

    public partial class ValidateRequest
    {
        public static ValidateRequest FromJson(string json) => JsonConvert.DeserializeObject<ValidateRequest>(json, Yggdrasil.Json.Validate.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ValidateRequest self) => JsonConvert.SerializeObject(self, Yggdrasil.Json.Validate.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
